# Generated by Django 3.1.8 on 2021-08-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='snippets',
            field=models.CharField(default='', max_length=1023),
        ),
    ]
